[package]
name = "replay_overlay"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
replay_core.workspace = true
fontdue.workspace = true
png.workspace = true
serde.workspace = true
serde_json.workspace = true
tiny-skia.workspace = true
unicode-linebreak.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
tempfile.workspace = true
